import type { Metadata } from "next";
import { font } from "./font";
import "@fontsource-variable/quicksand";
import "./globals.css";
import NavBar from "./NavBar";
import { Providers } from "./providers";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
	title: "Sarah K Yoga",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className={font.quicksand.variable}>
			<body>
				<Providers>
					<NavBar />
					<Box as="main" mt="60px">
						{children}
					</Box>
				</Providers>
			</body>
		</html>
	);
}
