import type { Metadata } from "next";
import { fonts } from "./fonts";
import "./globals.css";
import NavBar from "./NavBar";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body>
				<Providers>
					<NavBar />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
