import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Sarah K Yoga",
	description: "Generated by create next app",
};

const ServerLayout = ({ children }: { children: React.ReactNode }) => {
	return <>{children}</>;
};

export default ServerLayout;
